export const elements = {
  consonantBtnContainer: document.querySelector('#consonants'),
  consonantBtn: document.querySelector('#consonantBtn'),
  vowelBtnContainer: document.querySelector('#vowel'),
  vowelBtn: document.querySelector('#vowelBtn'),
  lettersCost: document.querySelector('.letters_box_cost'),
  wheel: document.querySelector('.wheel_box__wheel'),
  spinWheelBtn: document.querySelector('.wheel_box___spin-btn'),
  lettersContainer: document.querySelector('.letters_box'),
  initBtn: document.querySelector('.initial__form--btn'),
  initScreen: document.querySelector('.initial'),
  initForm: document.querySelector('.initial__form'),
  initFormValue: document.querySelector('.initial__form--input'),
  passwordCheckBtn: document.querySelector('#passwordCheckBtn'),
  passwordBtn: document.querySelector('#passwordBtn'),
  passwordForm: document.querySelector('#password__form'),
  userAnswerContainer: document.querySelector('.password'),
  readyScreenBtn: document.querySelector('#ready_btn'),
  readyScreenTimer: document.querySelector('#ready_timer'),
  readyScreen: document.querySelector('.ready_screen'),

  passwordsInputs: document.querySelectorAll('.password__input'),
  lettersBox: document.querySelectorAll('.letters_box__letters'),
  playerAvatar: document.querySelectorAll('.stats__avatar'),
  playerNick: document.querySelectorAll('.stats__nickname'),
  playerPointsContainers: document.querySelectorAll('.stats__points'),
  passwordContainer: document.querySelectorAll('.answers__password'),
  //answerPlaceholder: document.querySelectorAll('.answers__password')
}